CREATE DATABASE IF NOT EXISTS imc_db;
USE imc_db;

CREATE TABLE IF NOT EXISTS pessoas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    idade INT NOT NULL,
    altura DECIMAL(4, 2) NOT NULL,
    peso DECIMAL(5, 2) NOT NULL,
    imc DECIMAL(4, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);